### ISSUE TITLE
「同行者」の選択　２

### ISSUE THREAD

**Issue by MasanoriSatake** [code4fukui/fukui-kanko-survey#1]
[観光オープンデータ簡易分析(福井県外からの来訪者)](https://code4fukui.github.io/fukui-kanko-stat/withoutfukui.html) にも、「同行者」の選択も増やしていただけるとありがたいです。

**Comment by taisukef** [comment]
https://github.com/code4fukui/fukui-kanko-stat/issues/16
へ転記しました
