### ISSUE TITLE
ワードクラウド化について

### ISSUE THREAD

**Issue by MasanoriSatake** [code4fukui/fukui-kanko-survey#2]
[観光アンケートコメントマップ](https://code4fukui.github.io/sightseeingApp/)　を、ワードクラウドの形で表現することはできませんでしょうか？^^

http://wordcloudjp.com/

**Comment by taisukef** [comment]
このライブラリとか使うといいかも？
https://github.com/timdream/wordcloud2.js

**Comment by taisukef** [comment]
https://github.com/code4fukui/fukui-kanko-stat/issues/17
へ転記しました
